<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSe9hLdz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSe9hLdz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSe9hLdz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSe9hLdz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSe9hLdz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Se9hLdz',
    'container.build_id' => 'b2578987',
    'container.build_time' => 1751023811,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSe9hLdz');
