<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home_home' => [[], ['_controller' => 'App\\Controller\\AppController::home'], [], [['text', '/e10']], [], [], []],
    'home_tables' => [[], ['_controller' => 'App\\Controller\\AppController::tables'], [], [['text', '/e10/showTables']], [], [], []],
    'home_readFile' => [[], ['_controller' => 'App\\Controller\\AppController::readFile'], [], [['text', '/e10/readFile']], [], [], []],
    'save_orm_createTable' => [[], ['_controller' => 'App\\Controller\\SaveOrmController::createTable'], [], [['text', '/e10/saveOrm/createTable']], [], [], []],
    'save_sql_createTable' => [[], ['_controller' => 'App\\Controller\\SaveSqlController::createTable'], [], [['text', '/e10/saveSql/createTable']], [], [], []],
    'App\Controller\AppController::home' => [[], ['_controller' => 'App\\Controller\\AppController::home'], [], [['text', '/e10']], [], [], []],
    'App\Controller\AppController::tables' => [[], ['_controller' => 'App\\Controller\\AppController::tables'], [], [['text', '/e10/showTables']], [], [], []],
    'App\Controller\AppController::readFile' => [[], ['_controller' => 'App\\Controller\\AppController::readFile'], [], [['text', '/e10/readFile']], [], [], []],
    'App\Controller\SaveOrmController::createTable' => [[], ['_controller' => 'App\\Controller\\SaveOrmController::createTable'], [], [['text', '/e10/saveOrm/createTable']], [], [], []],
    'App\Controller\SaveSqlController::createTable' => [[], ['_controller' => 'App\\Controller\\SaveSqlController::createTable'], [], [['text', '/e10/saveSql/createTable']], [], [], []],
];
