<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEtDkc8y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEtDkc8y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEtDkc8y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEtDkc8y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEtDkc8y\App_KernelDevDebugContainer([
    'container.build_hash' => 'EtDkc8y',
    'container.build_id' => 'b16af562',
    'container.build_time' => 1750923447,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEtDkc8y');
