<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLKiFs9b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLKiFs9b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLKiFs9b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLKiFs9b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLKiFs9b\App_KernelDevDebugContainer([
    'container.build_hash' => 'LKiFs9b',
    'container.build_id' => 'e51b7296',
    'container.build_time' => 1750840483,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLKiFs9b');
