<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'address_createTable' => [[], ['_controller' => 'App\\Controller\\AddressController::createTable'], [], [['text', '/e08/address/createTable']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\AppController::home'], [], [['text', '/e08']], [], [], []],
    'bank_account_createTable' => [[], ['_controller' => 'App\\Controller\\BankAccountController::createTable'], [], [['text', '/e08/bank_account/createTable']], [], [], []],
    'person_createTable' => [[], ['_controller' => 'App\\Controller\\PersonController::createTablePersons'], [], [['text', '/e08/person/createTable']], [], [], []],
    'person_updateTable' => [[], ['_controller' => 'App\\Controller\\PersonController::updateTablePersons'], [], [['text', '/e08/person/updateTable']], [], [], []],
    'App\Controller\AddressController::createTable' => [[], ['_controller' => 'App\\Controller\\AddressController::createTable'], [], [['text', '/e08/address/createTable']], [], [], []],
    'App\Controller\AppController::home' => [[], ['_controller' => 'App\\Controller\\AppController::home'], [], [['text', '/e08']], [], [], []],
    'App\Controller\BankAccountController::createTable' => [[], ['_controller' => 'App\\Controller\\BankAccountController::createTable'], [], [['text', '/e08/bank_account/createTable']], [], [], []],
    'App\Controller\PersonController::createTablePersons' => [[], ['_controller' => 'App\\Controller\\PersonController::createTablePersons'], [], [['text', '/e08/person/createTable']], [], [], []],
    'App\Controller\PersonController::updateTablePersons' => [[], ['_controller' => 'App\\Controller\\PersonController::updateTablePersons'], [], [['text', '/e08/person/updateTable']], [], [], []],
];
