<?php

namespace ContainerLKiFs9b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBankAccountControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BankAccountController' shared autowired service.
     *
     * @return \App\Controller\BankAccountController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BankAccountController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Database.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BankAccountService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PersonService.php';

        $container->services['App\\Controller\\BankAccountController'] = $instance = new \App\Controller\BankAccountController(new \App\Service\BankAccountService(), ($container->privates['App\\Service\\PersonService'] ??= new \App\Service\PersonService()));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\BankAccountController', $container));

        return $instance;
    }
}
