<?php

namespace ContainerSe9hLdz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AppController' shared autowired service.
     *
     * @return \App\Controller\AppController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AppController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileReaderService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SaveSqlService.php';

        $container->services['App\\Controller\\AppController'] = $instance = new \App\Controller\AppController(new \App\Service\FileReaderService(), ($container->privates['App\\Service\\SaveSqlService'] ??= new \App\Service\SaveSqlService()), ($container->privates['App\\Service\\SaveOrmService'] ?? $container->load('getSaveOrmServiceService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\AppController', $container));

        return $instance;
    }
}
